"""PDF generation endpoints for tailored resumes.

Provides live preview and download endpoints for Typst-rendered PDFs.
Integrates with CP-15 tailored resume assembly pipeline.
"""

import asyncio
import logging
import re
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.database import get_db
from src.models import TailoredResume
from src.schemas.tailored_resume import TailoredResumeResponse
from src.services.pdf_generator import TypstCompilationError, generate_pdf

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/generate", tags=["generate"])


@router.get(
    "/preview/{job_id}",
    summary="Live preview PDF (inline) - INSTANT",
    response_class=Response
)
async def preview_pdf(
    job_id: UUID,
    db: AsyncSession = Depends(get_db)
) -> Response:
    """Generate and return PDF for inline browser preview (instant <2s).

    This endpoint returns the PDF with `Content-Disposition: inline` to
    allow browsers to display it directly (e.g., in an iframe or new tab).

    **Async Pattern - Pre-computed Data:**
    This endpoint fetches pre-computed tailored resume data from the database
    (generated by background task) instead of calling expensive LLM operations.
    This makes PDF generation instant (<2s) instead of timing out (2-3+ min).

    **Workflow:**
    1. Fetch pre-computed tailored resume from database
    2. Check status (pending/processing/completed/failed)
    3. Generate PDF using Typst compiler (if completed)
    4. Return PDF binary with inline disposition

    **Prerequisites:**
    - Job must be analyzed: POST /jobs/{job_id}/analyze
    - Tailored resume must be generated: POST /jobs/{job_id}/tailor
    - Resume must be completed (poll GET /jobs/{job_id}/tailor/status)

    Args:
        job_id: Job UUID
        db: Database session

    Returns:
        PDF binary stream with application/pdf content type

    Raises:
        HTTPException 404: Tailored resume not found
        HTTPException 202: Tailoring still in progress (pending/processing)
        HTTPException 500: Tailoring failed or PDF generation failed
        HTTPException 504: Compilation timeout

    Performance:
        <2 seconds total (Typst compilation only, no LLM calls)
    """
    try:
        logger.info(f"Generating preview PDF for job {job_id}")

        # Step 1: Fetch pre-computed tailored resume
        result = await db.execute(
            select(TailoredResume).where(TailoredResume.job_id == job_id)
        )
        tailored_record = result.scalar_one_or_none()

        if not tailored_record:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Tailored resume not found. Call POST /jobs/{job_id}/tailor first."
            )

        # Step 2: Check status
        if tailored_record.status in ["pending", "processing"]:
            raise HTTPException(
                status_code=status.HTTP_202_ACCEPTED,
                detail=f"Tailored resume {tailored_record.status}. Poll /jobs/{job_id}/tailor/status."
            )

        if tailored_record.status == "failed":
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Tailored resume generation failed: {tailored_record.error_message}"
            )

        # Step 3: Deserialize result
        tailored_resume = TailoredResumeResponse(**tailored_record.result_json)

        # Step 4: Generate PDF (instant <2s)
        pdf_bytes = await generate_pdf(tailored_resume)

        # Step 5: Return PDF with inline disposition
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": "inline; filename=preview.pdf"
            }
        )

    except HTTPException:
        raise
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="PDF generation timed out (>5s). Template may be too complex."
        )
    except TypstCompilationError as e:
        logger.error(f"Typst compilation failed for job {job_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF compilation failed: {str(e)}"
        )
    except Exception as e:
        logger.error(f"PDF preview failed for job {job_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF preview generation failed: {str(e)}"
        )


@router.get(
    "/download/{job_id}",
    summary="Download PDF with clean filename - INSTANT",
    response_class=Response
)
async def download_pdf(
    job_id: UUID,
    db: AsyncSession = Depends(get_db)
) -> Response:
    """Generate and download PDF with a clean, descriptive filename (instant <2s).

    This endpoint returns the PDF with `Content-Disposition: attachment` to
    trigger a browser download with a clean filename:
    `FirstName_LastName_CompanyName_Resume.pdf`

    **Async Pattern - Pre-computed Data:**
    This endpoint fetches pre-computed tailored resume data from the database
    (generated by background task) instead of calling expensive LLM operations.
    This makes PDF generation instant (<2s) instead of timing out (2-3+ min).

    **Filename Format:**
    - Example: `John_Doe_Google_Resume.pdf`
    - Spaces replaced with underscores
    - Special characters removed

    **Workflow:**
    1. Fetch pre-computed tailored resume from database
    2. Check status (pending/processing/completed/failed)
    3. Generate PDF using Typst compiler (if completed)
    4. Construct clean filename from resume metadata
    5. Return PDF with attachment disposition

    Args:
        job_id: Job UUID
        db: Database session

    Returns:
        PDF binary stream with attachment disposition

    Raises:
        HTTPException 404: Tailored resume not found
        HTTPException 202: Tailoring still in progress (pending/processing)
        HTTPException 500: Tailoring failed or PDF generation failed
        HTTPException 504: Compilation timeout

    Note:
        Personal info (first/last name) uses placeholders until User model
        is implemented in CP-17. Current filename: "John_Doe_CompanyName_Resume.pdf"
    """
    try:
        logger.info(f"Generating download PDF for job {job_id}")

        # Step 1: Fetch pre-computed tailored resume
        result = await db.execute(
            select(TailoredResume).where(TailoredResume.job_id == job_id)
        )
        tailored_record = result.scalar_one_or_none()

        if not tailored_record:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Tailored resume not found. Call POST /jobs/{job_id}/tailor first."
            )

        # Step 2: Check status
        if tailored_record.status in ["pending", "processing"]:
            raise HTTPException(
                status_code=status.HTTP_202_ACCEPTED,
                detail=f"Tailored resume {tailored_record.status}. Poll /jobs/{job_id}/tailor/status."
            )

        if tailored_record.status == "failed":
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Tailored resume generation failed: {tailored_record.error_message}"
            )

        # Step 3: Deserialize result
        tailored_resume = TailoredResumeResponse(**tailored_record.result_json)

        # Step 4: Generate PDF (instant <2s)
        pdf_bytes = await generate_pdf(tailored_resume)

        # Step 5: Construct clean filename
        # Format: FirstName_LastName_CompanyName_Resume.pdf
        # TODO: Extract first/last name from User model (CP-17)
        first_name = "John"  # Placeholder
        last_name = "Doe"   # Placeholder
        company_name = tailored_resume.company_name.replace(" ", "_")

        # Remove special characters from company name
        company_clean = re.sub(r'[^A-Za-z0-9_]', '', company_name)

        filename = f"{first_name}_{last_name}_{company_clean}_Resume.pdf"

        logger.info(f"Download filename: {filename}")

        # Step 6: Return PDF with attachment disposition
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"'
            }
        )

    except HTTPException:
        raise
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="PDF generation timed out (>5s). Template may be too complex."
        )
    except TypstCompilationError as e:
        logger.error(f"Typst compilation failed for job {job_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF compilation failed: {str(e)}"
        )
    except Exception as e:
        logger.error(f"PDF download failed for job {job_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF download generation failed: {str(e)}"
        )
